### PR TITLE
Show a humanized ETA

### LINKED ISSUE #122: Show download estimated time of arrival
First of all, this is an amazing project! I've just used it with my smartphone.

Second of all, I suggest you to show user-friendly ETA text.
I've searched in the docs of both webtorrent and webrtc for any ETA text output, but didn't find anything, so it seems like it should be calculated on the fly.

### PR DESCRIPTION
**Pull request by toXel**
Fixes #122

### CODE REVIEW

**Comment by toXel** [comment]
@feross Is there something wrong with this PR?

**Comment by revolunet** [comment]
i guess moment is a pretty big dependency. maybe https://github.com/EvanHahn/HumanizeDuration.js or another smaller lib would be more appropriate ?

**Comment by toXel** [comment]
@revolunet Yea that is a good idea I think. I've used moment.js because it's also used on the WebTorrent homepage.

**Comment by feross** [comment]
Since this is already used on the webtorrent homepage, I think it's fine for now. But @revolunet is right that we shouldn't require all 16KB of moment just to use one function 👍

**Pull request merged**
